# Alpine Container Configuration

# Settings For Final Container
dockerUser=geoffh1977
finalImageName=alpine
finalImageVersion=3.9
timeZone='Australia/Melbourne'
alpineUser=user
alpineUid=1000
alpineGid=1000

# Build Container Variables
buildImageName=alpine
buildImageVersion=latest
buildAlpineVersion=v${finalImageVersion}
buildBaseUrl='http://nl.alpinelinux.org/alpine'
