# Builds Alpine Filesystem
FROM {{ buildImageName + ":" + buildImageVersion }} AS build

COPY scripts/mkimage-alpine.bash scripts/apk-install /
RUN chmod u+x /apk-install /mkimage-alpine.bash && \
    sync && \
    /apk-install bash tzdata && \
    /mkimage-alpine.bash -E -c -t {{ timeZone }} -r v{{ alpineDirVersion }} -m {{ alpineBaseUrl }}

# Build New Alpine Container And Secure With Non-Root Access
FROM scratch AS release
LABEL maintainer="{{ dockerUser }} <{{ dockerUserEmail }}>"

COPY --from=build /var/tmp/rootfs/ /

ENV ALPINE_USER={{ alpineUser }} \
    ALPINE_UID={{ alpineUid }} \
    ALPINE_GID={{ alpineGid }} \
    ALPINE_VERSION={{ finalImageVersion }}

RUN addgroup -g ${ALPINE_GID} ${ALPINE_USER} && adduser -D -u ${ALPINE_UID} -G ${ALPINE_USER} ${ALPINE_USER}

USER ${ALPINE_USER}
WORKDIR /home/{{ alpineUser }}
CMD ["/bin/sh"]
